AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - org.example::AWS-lambda-check-datasource
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsLambdaCheckDatasourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.martinatanasov.test.datasource.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get

Outputs:
  AwsLambdaCheckDatasourceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getUsersInfo'
    Export:
      Name: AwsLambdaCheckDatasourceApi
